name: Sync branches

on:
  push:
    branches:
      - master # 
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync backend-only branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            git checkout backend-only
            git pull origin master
            git push origin backend-only
          fi
